id: I49474AC5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T05:17:00+00:00'
last_modified: '2022-06-16T04:04:35.331742+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20311
  title: ཕྱུགས་ལས་ཀྱི་རྒྱུན་ཤེས་ཀློག་དེབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    45D3:
      image_group_id: I8LS20313
      title: Volume 1 of phyugs las kyi rgyun shes klog deb/
      total_pages: 237
      order: 1
      base_file: 45D3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
